version: '3.8'

services:
  fastapi-main:
    build: ./services/fastapi-main
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  kyusei-service:
    build: ./services/kyusei-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  seimei-service:
    build: ./services/seimei-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  microservices-network:
    driver: bridge