"""Initial migration

Revision ID: ba07018db0e3
Revises: 
Create Date: 2025-09-23 09:42:43.466871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba07018db0e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('kantei_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_birth_date', sa.String(), nullable=False),
    sa.Column('kyusei_result', sa.Text(), nullable=True),
    sa.Column('seimei_result', sa.Text(), nullable=True),
    sa.Column('combined_result', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('pdf_generated', sa.Boolean(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kantei_records_id'), 'kantei_records', ['id'], unique=False)
    op.create_table('template_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('company_logo_path', sa.String(), nullable=True),
    sa.Column('pdf_header_text', sa.Text(), nullable=True),
    sa.Column('pdf_footer_text', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('include_company_info', sa.Boolean(), nullable=True),
    sa.Column('include_logo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_settings_id'), 'template_settings', ['id'], unique=False)
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kantei_record_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kantei_record_id'], ['kantei_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_history_id'), 'email_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_history_id'), table_name='email_history')
    op.drop_table('email_history')
    op.drop_index(op.f('ix_template_settings_id'), table_name='template_settings')
    op.drop_table('template_settings')
    op.drop_index(op.f('ix_kantei_records_id'), table_name='kantei_records')
    op.drop_table('kantei_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
