name: Deploy to Cloud Run

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker

    # 九星気学サービスのデプロイ（最初）
    - name: Build and Deploy Kyusei Service
      run: |
        cd services/kyusei-service
        docker build -t gcr.io/$GCP_PROJECT_ID/kyusei-service .
        docker push gcr.io/$GCP_PROJECT_ID/kyusei-service
        gcloud run deploy kyusei-service \
          --image gcr.io/$GCP_PROJECT_ID/kyusei-service \
          --region $GCP_REGION \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 0.5 \
          --max-instances 5

    # 姓名判断サービスのデプロイ（次）
    - name: Build and Deploy Seimei Service
      run: |
        cd services/seimei-service
        docker build -t gcr.io/$GCP_PROJECT_ID/seimei-service .
        docker push gcr.io/$GCP_PROJECT_ID/seimei-service
        gcloud run deploy seimei-service \
          --image gcr.io/$GCP_PROJECT_ID/seimei-service \
          --region $GCP_REGION \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 0.5 \
          --max-instances 5

    # FastAPI 統合サービスのデプロイ（最後）
    - name: Get Microservice URLs and Deploy FastAPI Service
      run: |
        # マイクロサービスのURLを取得
        KYUSEI_URL=$(gcloud run services describe kyusei-service --region=$GCP_REGION --format="get(status.url)")
        SEIMEI_URL=$(gcloud run services describe seimei-service --region=$GCP_REGION --format="get(status.url)")

        # FastAPIサービスをデプロイ
        cd services/fastapi-main
        docker build -t gcr.io/$GCP_PROJECT_ID/unmeiori-api .
        docker push gcr.io/$GCP_PROJECT_ID/unmeiori-api
        gcloud run deploy unmeiori-api \
          --image gcr.io/$GCP_PROJECT_ID/unmeiori-api \
          --region $GCP_REGION \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --set-env-vars JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
          --set-env-vars CORS_ORIGIN="${{ secrets.CORS_ORIGIN }}" \
          --set-env-vars KYUSEI_SERVICE_URL="$KYUSEI_URL" \
          --set-env-vars SEIMEI_SERVICE_URL="$SEIMEI_URL"

    # サービスURLの出力
    - name: Get Service URLs
      run: |
        echo "FastAPI Service URL:"
        gcloud run services describe unmeiori-api --region=$GCP_REGION --format="get(status.url)"
        echo "Kyusei Service URL:"
        gcloud run services describe kyusei-service --region=$GCP_REGION --format="get(status.url)"
        echo "Seimei Service URL:"
        gcloud run services describe seimei-service --region=$GCP_REGION --format="get(status.url)"